import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {  ModalProvider } from "@/providers/modal-provider";
import {Toaster} from "@/components/ui/sonner"
import { ConvexClientProvider } from "@/providers/convex-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CO-OP BOARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster/>
          <ModalProvider/>
        {children}
        </ConvexClientProvider>
        
        </body>
    </html>
  );
}
